### ISSUE TITLE
Bizagi de ICP

### ISSUE THREAD

**Issue by isaireyesp1** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-bleachers#1]
[Reporte practica 2 (2).pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-bleachers/files/12822918/Reporte.practica.2.2.pdf)

**Comment by Eve-lizet** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
